# Generated by Django 5.1.3 on 2024-11-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('category', models.CharField(choices=[('Veg', 'Veg-Pizza'), ('Non-Veg', 'Non-veg Pizza'), ('Combo', 'Combo')], max_length=10)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact Table'},
        ),
    ]
